### ISSUE TITLE
앨범 페이지 제작

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MC3-Team5-CleanArea#16]
## 🛠 Issue
앨범 페이지를 제작합니다.

## 📝 To-do

- [x] 앨범 페이지 가이드
- [x] 좋아요 기능
- [x] 사진 올린 시간 추가
- [x] 앨범 피드에 내가 좋아요 한 사진은 오른쪽 상단에 하트 표시
- [x] 친구 추가 하는 버튼 추가
