### ISSUE TITLE
Notification 페이지 제작

### ISSUE THREAD

**Issue by 4shimi** [DeveloperAcademy-POSTECH/MC3-Team5-CleanArea#23]
## 🛠 Issue
노티피케이션 페이지를 제작합니다.

## 📝 To-do

- [ ]노티 view
- [ ]노티 같은날은 쌓이는 로직 및 UI
- [ ]터치시 같이 초대 받은 친구들의 얼굴(3인)과 나머지의 숫자가 순차적으로 애니메이션효과
- [ ]여우 종류 별 6가지 타입의 여우의 역할 선택 가능한 선택지 (output) 출력

**Comment by 4shimi** [comment]
노티 데이터 파베 데이터 연결빼고는 MOCKUP DATA로 연결하여 구현해 두었습니다.
