### ISSUE TITLE
개인 설정 페이지 제작

### ISSUE THREAD

**Issue by 4shimi** [DeveloperAcademy-POSTECH/MC3-Team5-CleanArea#24]
## 🛠 Issue
개인 설정 페이지를 제작합니다

## 📝 To-do

- [x] 설정 view 제작
- [x] 토글 알람 제작
- [x] 알람 로직 제작
- [x] 프로필 수정 페이지 제작(사진, 닉네임, 아이디)

<img width="150" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team5-CleanArea/assets/104481869/9801c3b0-075a-4004-8fa2-1093f3d0ba82">

<img width="150" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team5-CleanArea/assets/104481869/67bfd565-156b-4b14-afe7-7215f66e0897">

<img width="150" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team5-CleanArea/assets/104481869/4ca3b11d-2d2c-47e1-8315-d9b70453d833">
