### ISSUE TITLE
노티 기능 구현

### ISSUE THREAD

**Issue by 4shimi** [DeveloperAcademy-POSTECH/MC3-Team5-CleanArea#34]
## 🛠 Issue
noti 기능 구현

## 📝 To-do

- [x] (여행중)촬영 제안 셀프 푸시 기능 구현
- [x] (여행전)여행 시작 푸시 기능 구현
- [x] (여행후) 추억 회상 푸시 기능 구현
- [x] + Jamie 수정사항

<img width="180" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team5-CleanArea/assets/104481869/03876ccf-15ad-445b-ab0e-da07e7f60a48">

<img width="180" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team5-CleanArea/assets/104481869/25bd5242-a304-4541-be66-2fab1b95553e">

<img width="180" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team5-CleanArea/assets/104481869/34ba750e-9800-44c2-9354-5977164f6e2d">
