### ISSUE TITLE
이미지 상세 페이지 메뉴 기능 구현 및 연결

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MC3-Team5-CleanArea#35]
## 🛠 Issue
이미지 상세 페이지에 메뉴 기능을 구현합니다.

## 📝 To-do

- [x] 앨범 제목 수정하기
- [x] 여행 종료하기 로직
- [x] 여행 삭제하기 로직
- [x] 사진 저장
- [x] 대표 이미지 설정
- [x] 삭제

---

- [x] 앨범 제목 수정하기 연결
- [x] 여행 종료하기 로직 연결
- [x] 여행 삭제하기 로직 연결
- [x] 사진 저장 연결
- [x] 대표 이미지 설정 연결
- [x] 삭제 연결
