### ISSUE TITLE
앨범 페이지 상세 세팅 + UT 피드백 적용

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MC3-Team5-CleanArea#36]
## 🛠 Issue
앨범 페이지를 피그마에 맞게 UI 세팅합니다.

## 📝 To-do

- [x] 갤러리 보이는 뷰 토글 순서 변경하기
- [ ] 갤러리 스와이프로 넘어가기
- [x] 시간 순 sort 기능

---

- [x] 페이징 처리
- [x] 이미지 캐시 처리
- [x] 코드 리팩토링
