### ISSUE TITLE
알림, 설정페이지 변경사항

### ISSUE THREAD

**Issue by 4shimi** [DeveloperAcademy-POSTECH/MC3-Team5-CleanArea#44]
## 🛠 Issue
알림,설정페이지 변경사항 (7월24일) 변경사항

## 📝 To-do

- [x] 배경 색상변경, 텍스트 및 하단 라인
- [x] 네비게이션바: 하단 라인 추가
- [x] 리스트 셀 섀도우값 변경
- [x] 회원탈퇴/로그인 버튼: 색상 변경 및 스트로크 추가
