### ISSUE TITLE
1차 테스트 후 버그 픽스

### ISSUE THREAD

**Issue by pingse** [DeveloperAcademy-POSTECH/MC3-Team5-CleanArea#63]
## 🛠 Issue
테스트를 하면서 발견한 버그들을 픽스

## 📝 To-do

- [ ] 카메라 처음 권한 받을 때 터지는 현상
- [ ] 로그인 후 닉네임이 고정적으로 아지로 나오다가 플로우 한번 거친 후에 정상적으로 작동하는 현상
- [ ] 앨범이 없음에도 과거 앨범 멘트가 나오는 부분
