### ISSUE TITLE
Camera 기능 구현

### ISSUE THREAD

**Issue by pingse** [DeveloperAcademy-POSTECH/MC3-Team5-CleanArea#7]
## 🛠 Issue
- 카메라 기능을 구현
- 동영상 / 사진을 찍고 확인 후 저장
- 미리보기 화면 구현

## 📝 To-do

- [x] 카메라 기능 커스텀
- [x] 동영상 / 사진 기능 넣기
- [x] 찍은 사진 / 동영상 Preview 구현
- [x] 동영상 / 사진 저장
